[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
runs = 256
max_test_rejects = 120000
seed = '0xB00B1E5'

[invariant]
runs = 256
depth = 256
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config